task :default => [:cc, :jar]

task :cc do
  system "javac -sourcepath src -d classes -cp #{jars}:. " + sources
end

task :jar do
  Dir.chdir 'classes'
  system "jar cf ../lib/sample.jar " + classes
  Dir.chdir '..'
end

def sources
  Dir["./src/**/*.java"].join(' ')
end

def classes
  Dir["./**/*.class"].join(' ')
end

def jars
  Dir["./lib/**/*.jar"].join(':')
end

