task :init do
  boxes = `vagrant box list`
  if(/precise32/m.match boxes)
    puts 'box precise32 already defined.'
  else
    system 'vagrant init precise32 http://files.vagrantup.com/precise32.box'
  end
end

task :up do
  system 'vagrant up'
end

task :destroy do
  system 'vagrant destroy'
end

task :start do
  system "vagrant ssh -c 'cd /vagrant/mall; foreman start'"
end

task :test do
  system "vagrant ssh -c 'cd /vagrant/mall/kiosks/JavaHello; cucumber -s'"
end

task :tar do
  system "cd ..; tar czf kiosk.tar.gz --exclude kiosk/.git --exclude kiosk/.vagrant helloworld"
end
