# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "precise32"

  #forward kiosk ports

  config.vm.forward_port 9901, 9901
  config.vm.forward_port 9902, 9902
  config.vm.forward_port 9903, 9903
  config.vm.forward_port 9904, 9904
  config.vm.forward_port 9905, 9905
  config.vm.forward_port 9906, 9906
  config.vm.forward_port 9907, 9907
  config.vm.forward_port 9908, 9908
  config.vm.forward_port 9909, 9909
  config.vm.forward_port 9910, 9910

  config.vm.provision :puppet, :module_path => ENV['KIOSK_GEM_DIR'] + "/provision/modules" do |puppet|
    puppet.manifests_path = ENV['KIOSK_GEM_DIR'] + "/provision/manifests"
    puppet.manifest_file  = "default.pp"
  end
  config.vm.provision :shell, :path => ENV['KIOSK_GEM_DIR'] + "/provision/bootstrap.sh"
end
