task :client do
  system "KIOSK_TEST='http://localhost:9902/com.countabout.yodlee.kiosk' java -cp 'classes:lib/*' sample.JavaClient"
end

task :client_cc do
  system "javac -sourcepath src -d classes -cp lib/json-simple-1.1.1.jar:lib/kiosk.jar:. src/sample/JavaClient.java src/sample/SampleKiosk.java"
end

task :kiosk_cc do
  system "javac -sourcepath src -d classes -cp lib/json-simple-1.1.1.jar:. src/org/toolshed/kiosk/Kiosk.java src/org/toolshed/kiosk/RemoteService.java src/org/toolshed/kiosk/Poster.java src/org/toolshed/kiosk/KioskProxy.java src/org/toolshed/kiosk/Greeter.java src/org/toolshed/kiosk/Hellos.java"
end

task :kiosk_jar do
  system "cd classes; jar cf ../lib/kiosk.jar org/toolshed/kiosk/Kiosk.class org/toolshed/kiosk/RemoteService.class org/toolshed/kiosk/Poster.class org/toolshed/kiosk/KioskProxy.class org/toolshed/kiosk/Greeter.class org/toolshed/kiosk/Hellos.class"
end
