task :init do
  boxes = `vagrant box list`
  if(/precise32/m.match boxes)
    puts 'box precise32 already defined.'
  else
    system 'vagrant init precise32 http://files.vagrantup.com/precise32.box'
  end
end

task :up do
  system 'vagrant up'
end

task :destroy do
  system 'vagrant destroy'
end

task :start do
  exec "vagrant ssh -c 'cd /vagrant/mall; /usr/local/bin/rake start'"
end

task :log do
  exec "vagrant ssh -c 'cd /vagrant/mall; /usr/local/bin/rake log'"
end

task :stop do
  exec "vagrant ssh -c 'cd /vagrant/mall; /usr/local/bin/rake stop'"
end

task :rubytest do
  system "vagrant ssh -c 'cd /vagrant/mall/kiosks/HelloWorldKiosk; env KIOSK_LOGGER=ruby:///OutputLogger cucumber -s'"
end

task :javatest do
  system "vagrant ssh -c 'cd /vagrant/mall/kiosks/JavaHello; cucumber -s'"
end

task :tar do
  system "cd ..; tar czf kiosk.tar.gz --exclude kiosk/.git --exclude kiosk/.vagrant helloworld"
end

task :curl do
  #curl -X POST -H "application/json" -d '{"key":"val"}' http://10.0.2.210:4000/Toolshed/HelloWorldKiosk/list
end
