task :cc do
  system "javac -sourcepath src -d classes src/com/countabout/yodlee/kiosk/YodleeUserKiosk.java src/sample/JavaHello.java src/sample/work/JavaHello.java"
end

task :jar do
  system "cd classes; jar cf ../lib/JavaHello.jar com/countabout/yodlee/kiosk/YodleeUserKiosk.class sample/JavaHello.class sample/work/JavaHello.class"
end
