task :default => [:client_cc, :client]
task :client do
  system "foreman run -e 'development.env' java -cp 'classes:lib/*' org.toolshed.kiosk.Arcade"
end

task :client_cc do
  system "javac -sourcepath src -d classes -cp #{jars}:. " + client_sources
end

def client_sources
  Dir["./src/**/*.java"].join(' ')
end

def jars
  Dir["./lib/**/*.jar"].join(':')
end
